-- CCC Calificados: cierres históricos por sucursal y período.
-- Guarda una copia inmutable del resultado procesado del dashboard para poder
-- consultar meses anteriores aunque luego cambien los archivos fuente.

begin;

create table if not exists public.ccc_dashboard_snapshots (
  id bigint generated by default as identity primary key,
  branch_key text not null,
  period_year integer not null,
  period_month integer not null,
  source_fingerprint text,
  brand_config jsonb not null default '[]'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  closed_by uuid references public.profiles(id) on delete set null,
  closed_by_name text,
  closed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ccc_dashboard_snapshots_period_month_check check (period_month between 1 and 12),
  constraint ccc_dashboard_snapshots_period_year_check check (period_year between 2020 and 2100),
  constraint ccc_dashboard_snapshots_branch_period_unique unique (branch_key, period_year, period_month)
);

create index if not exists ccc_dashboard_snapshots_branch_period_idx
  on public.ccc_dashboard_snapshots(branch_key, period_year desc, period_month desc);

alter table public.ccc_dashboard_snapshots enable row level security;

drop policy if exists ccc_dashboard_snapshots_select_authenticated on public.ccc_dashboard_snapshots;
create policy ccc_dashboard_snapshots_select_authenticated
on public.ccc_dashboard_snapshots
for select
to authenticated
using (true);

drop policy if exists ccc_dashboard_snapshots_insert_admin on public.ccc_dashboard_snapshots;
create policy ccc_dashboard_snapshots_insert_admin
on public.ccc_dashboard_snapshots
for insert
to authenticated
with check (
  public.my_role() = 'admin'
  and closed_by = auth.uid()
);

drop policy if exists ccc_dashboard_snapshots_update_admin on public.ccc_dashboard_snapshots;
create policy ccc_dashboard_snapshots_update_admin
on public.ccc_dashboard_snapshots
for update
to authenticated
using (public.my_role() = 'admin')
with check (
  public.my_role() = 'admin'
  and closed_by = auth.uid()
);

drop policy if exists ccc_dashboard_snapshots_delete_admin on public.ccc_dashboard_snapshots;
create policy ccc_dashboard_snapshots_delete_admin
on public.ccc_dashboard_snapshots
for delete
to authenticated
using (public.my_role() = 'admin');

grant select, insert, update, delete on public.ccc_dashboard_snapshots to authenticated;

commit;
